---
name: Releases

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/${{ github.repository_owner }}
      - name: Build node
        run: npm ci
      - name: Publish node package
        run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
